require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkdaysController do

  # This should return the minimal set of attributes required to create a valid
  # Workday. As you add validations to Workday, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all workdays as @workdays" do
      workday = Workday.create! valid_attributes
      get :index
      assigns(:workdays).should eq([workday])
    end
  end

  describe "GET show" do
    it "assigns the requested workday as @workday" do
      workday = Workday.create! valid_attributes
      get :show, :id => workday.id
      assigns(:workday).should eq(workday)
    end
  end

  describe "GET new" do
    it "assigns a new workday as @workday" do
      get :new
      assigns(:workday).should be_a_new(Workday)
    end
  end

  describe "GET edit" do
    it "assigns the requested workday as @workday" do
      workday = Workday.create! valid_attributes
      get :edit, :id => workday.id
      assigns(:workday).should eq(workday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Workday" do
        expect {
          post :create, :workday => valid_attributes
        }.to change(Workday, :count).by(1)
      end

      it "assigns a newly created workday as @workday" do
        post :create, :workday => valid_attributes
        assigns(:workday).should be_a(Workday)
        assigns(:workday).should be_persisted
      end

      it "redirects to the created workday" do
        post :create, :workday => valid_attributes
        response.should redirect_to(Workday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workday as @workday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workday.any_instance.stub(:save).and_return(false)
        post :create, :workday => {}
        assigns(:workday).should be_a_new(Workday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workday.any_instance.stub(:save).and_return(false)
        post :create, :workday => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workday" do
        workday = Workday.create! valid_attributes
        # Assuming there are no other workdays in the database, this
        # specifies that the Workday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Workday.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => workday.id, :workday => {'these' => 'params'}
      end

      it "assigns the requested workday as @workday" do
        workday = Workday.create! valid_attributes
        put :update, :id => workday.id, :workday => valid_attributes
        assigns(:workday).should eq(workday)
      end

      it "redirects to the workday" do
        workday = Workday.create! valid_attributes
        put :update, :id => workday.id, :workday => valid_attributes
        response.should redirect_to(workday)
      end
    end

    describe "with invalid params" do
      it "assigns the workday as @workday" do
        workday = Workday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workday.any_instance.stub(:save).and_return(false)
        put :update, :id => workday.id, :workday => {}
        assigns(:workday).should eq(workday)
      end

      it "re-renders the 'edit' template" do
        workday = Workday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workday.any_instance.stub(:save).and_return(false)
        put :update, :id => workday.id, :workday => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workday" do
      workday = Workday.create! valid_attributes
      expect {
        delete :destroy, :id => workday.id
      }.to change(Workday, :count).by(-1)
    end

    it "redirects to the workdays list" do
      workday = Workday.create! valid_attributes
      delete :destroy, :id => workday.id
      response.should redirect_to(workdays_url)
    end
  end

end
